FROM node:24-alpine

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

COPY package.json package-lock.json turbo.json ./
COPY apps ./apps
COPY packages ./packages
COPY services ./services

RUN npm install --global npm@11.6.1 \
    && npm ci

ARG WORKSPACE
ARG NEXT_PUBLIC_API_URL

ENV WORKSPACE=$WORKSPACE \
    NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

RUN npm run db:generate --workspace="$WORKSPACE" --if-present \
    && npm run build --workspace="$WORKSPACE"

ENV NODE_ENV=production

CMD ["sh", "-c", "npm run start --workspace=$WORKSPACE"]
