"use client";
import { useState } from "react";
import { AlertTriangle, BookOpenCheck, Braces, CalendarClock, ChevronRight, CirclePlus, ClipboardCheck, FileQuestion, GraduationCap, LayoutDashboard, MoreHorizontal, Users } from "lucide-react";
import { AppShell, StatusPill } from "@repo/ui/shell";
import { Button } from "@repo/ui/button";
import { Card } from "@repo/ui/card";
import { Metric } from "@repo/ui/metric";

const exams = [{ title: "Arrays & Hashing · Midterm", className: "DSA · Section A", date: "Sep 18, 10:00", submissions: "28 / 32", status: "Scheduled" }, { title: "Graph Traversal Quiz", className: "Algorithms · Section B", date: "Sep 14, 14:30", submissions: "41 / 41", status: "Review" }, { title: "Complexity Fundamentals", className: "DSA · Section A", date: "Sep 08, 09:00", submissions: "32 / 32", status: "Published" }];
export default function TeacherDashboard() {
  const [modal, setModal] = useState(false);
  return <AppShell role="Teacher" name="Maya Rao" initials="MR" navigation={[{ label: "Overview", active: true, icon: <LayoutDashboard size={17} /> }, { label: "Classes", icon: <Users size={17} /> }, { label: "Question bank", icon: <FileQuestion size={17} /> }, { label: "Exams", icon: <BookOpenCheck size={17} /> }, { label: "Review & grading", icon: <ClipboardCheck size={17} /> }]}>
    <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-xs font-bold uppercase text-[#176B5B]">Teacher workspace</p><h1 className="text-2xl font-bold">Your assessment desk</h1><p className="mt-1 text-sm text-[#6E7B76]">Create questions, schedule exams, and review evidence with context.</p></div><div className="flex gap-2"><Button variant="secondary" onClick={() => setModal(true)}><Braces size={16} /> New question</Button><Button><CirclePlus size={16} /> Create exam</Button></div></div>
    <Card className="mb-6 grid grid-cols-2 py-5 lg:grid-cols-4"><Metric label="Active classes" value="4" detail="128 enrolled students" icon={<GraduationCap size={18} />} /><Metric label="Question bank" value="86" detail="42 coding · 44 MCQ" icon={<FileQuestion size={18} />} /><Metric label="Needs review" value="17" detail="Across 2 completed exams" icon={<ClipboardCheck size={18} />} /><Metric label="Flagged edits" value="6" detail="Evidence, not verdicts" icon={<AlertTriangle size={18} />} /></Card>
    <div className="grid gap-6 xl:grid-cols-[1.45fr_0.8fr]"><Card><div className="flex items-center justify-between border-b border-[#E4E8E4] px-5 py-4"><div><h2 className="font-bold">Recent exams</h2><p className="text-xs text-[#7B8883]">Scheduled, review, and published work</p></div><button aria-label="Exam menu" className="text-[#75827D]"><MoreHorizontal size={18} /></button></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead className="bg-[#F7F8F6] text-[11px] uppercase text-[#7B8883]"><tr><th className="px-5 py-3">Exam</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">Submissions</th><th className="px-4 py-3">Status</th><th></th></tr></thead><tbody className="divide-y divide-[#EDF0ED]">{exams.map((exam) => <tr key={exam.title} className="hover:bg-[#FAFBF9]"><td className="px-5 py-4"><div className="text-sm font-semibold">{exam.title}</div><div className="text-xs text-[#87928E]">{exam.className}</div></td><td className="px-4 py-4 text-sm text-[#596761]">{exam.date}</td><td className="px-4 py-4 text-sm font-medium">{exam.submissions}</td><td className="px-4 py-4"><StatusPill tone={exam.status === "Review" ? "amber" : exam.status === "Published" ? "green" : "neutral"}>{exam.status}</StatusPill></td><td className="px-4"><ChevronRight size={16} className="text-[#8A9691]" /></td></tr>)}</tbody></table></div></Card>
      <Card><div className="border-b border-[#E4E8E4] px-5 py-4"><h2 className="font-bold">Upcoming</h2><p className="text-xs text-[#7B8883]">Next seven days</p></div><div className="p-5"><div className="border-l-2 border-[#176B5B] pl-4"><div className="text-xs font-bold uppercase text-[#176B5B]">Thursday · 10:00</div><div className="mt-1 text-sm font-semibold">Arrays & Hashing · Midterm</div><div className="mt-1 text-xs text-[#78847F]">32 students · 75 minutes</div></div><div className="my-5 h-px bg-[#E7EAE7]" /><div className="flex items-start gap-3"><CalendarClock size={17} className="mt-0.5 text-[#986F1C]" /><div><div className="text-sm font-semibold">Question snapshot locks in 18h</div><p className="mt-1 text-xs leading-5 text-[#7A8782]">Changes to the source question will no longer affect this exam.</p></div></div></div></Card></div>
    {modal && <div className="fixed inset-0 z-50 grid place-items-center bg-[#0F1C18]/45 p-4"><div role="dialog" aria-modal="true" aria-label="New coding question" className="w-full max-w-lg rounded-lg bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-[#E2E6E3] px-5 py-4"><div><h2 className="font-bold">New coding question</h2><p className="text-xs text-[#7D8984]">Function signature · weighted tests</p></div><button onClick={() => setModal(false)} className="text-sm font-semibold text-[#64716C]">Close</button></div><div className="space-y-4 p-5"><label className="block text-xs font-semibold">Title<input defaultValue="Two Sum" className="mt-1.5 h-9 w-full rounded-md border border-[#D8DED9] px-3 text-sm" /></label><div className="grid grid-cols-2 gap-3"><label className="block text-xs font-semibold">LeetCode number<input defaultValue="1" className="mt-1.5 h-9 w-full rounded-md border border-[#D8DED9] px-3 text-sm" /></label><label className="block text-xs font-semibold">Maximum marks<input defaultValue="16" className="mt-1.5 h-9 w-full rounded-md border border-[#D8DED9] px-3 text-sm" /></label></div><label className="block text-xs font-semibold">Function name<input defaultValue="twoSum" className="mt-1.5 h-9 w-full rounded-md border border-[#D8DED9] px-3 font-mono text-sm" /></label><div className="rounded-md border border-[#E8DFC0] bg-[#FFF9E9] p-3 text-xs leading-5 text-[#715721]">The reference is stored for attribution. Add only statement content and tests you are licensed to use.</div></div><div className="flex justify-end gap-2 border-t border-[#E2E6E3] px-5 py-4"><Button variant="secondary" onClick={() => setModal(false)}>Cancel</Button><Button onClick={() => setModal(false)}>Continue to tests</Button></div></div></div>}
  </AppShell>;
}
